version: '3.7'
services:
  client:
    build:
      context: ./app/
    command: npm start
    volumes:
      - ./app/:/app/
      - /app/node_modules
      - /app/public/coverage
    ports:
      - 3000:3000